SammysAuto/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SammysAuto.Data;

namespace SammysAuto.Controllers
{
    public class CustomersController : Controller
    {
        private readonly ApplicationDbContext _db;
        public CustomersController(ApplicationDbContext db) { _db = db; }
        protected override void Dispose(bool disposing) { _db.Dispose(); }

        public IActionResult Index()
        {
            ViewData["Title"] = "List of customers";
            ViewBag.AddController = "Account";
            ViewBag.CrudAction = "Register";
            var customers = _db.Users.ToList();  
            return View(customers);

        }

    }
}

SammysAuto/Controllers/ServiceTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SammysAuto.Data;
using SammysAuto.Models;

namespace SammysAuto.Controllers
{
    public class ServiceTypesController : Controller
    {

        public IActionResult Index()
        {
            ViewData["Title"] = "List of available services";
            ViewBag.CrudAction = "Add";

            var serviceTypes = _DbContext.ServiceTypes;

            //var webApi = new WebApiWrapper<ServiceType>(CommonCode.UrlCombine(CommonCode.GetAppUrl(HttpContext), "api", "ServiceTypeApi"));
            //var serviceTypes = webApi.Get();

            return View(serviceTypes);

        }

        public IActionResult Add()
        {
            ViewData["Title"] = "Adding a Service Type";
            ViewBag.CrudAction = "Create"; 

            return View("Edit", new ServiceType());

        }

        public IActionResult Edit(int id)
        {
            ViewData["Title"] = "Editing a Service Type";
            ViewBag.CrudAction = "Update";

            var serviceTypes = _DbContext.ServiceTypes;
            var serviceType = serviceTypes.Find(id); // find by primary key

            //var webApi = new WebApiWrapper<ServiceType>(CommonCode.UrlCombine(CommonCode.GetAppUrl(HttpContext), "api", "ServiceTypeApi"));
            //var serviceType = webApi.Get(id.ToString());

            return View(serviceType);

        }

        [HttpPost][ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ServiceType serviceType)
        //public IActionResult Create(ServiceType serviceType)
        {
            ViewData["Title"] = "Adding a Service Type";
            if (!ModelState.IsValid) return View("Edit",serviceType);

            var serviceTypes = _DbContext.ServiceTypes;
            await serviceTypes.AddAsync(serviceType);
            await _DbContext.SaveChangesAsync();

            //var webApi = new WebApiWrapper<ServiceType>(CommonCode.UrlCombine(CommonCode.GetAppUrl(HttpContext), "api", "ServiceTypeApi"));
            //webApi.Post(serviceType);

            return RedirectToAction(GetIndexAction());

        }

        [HttpPost] [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(ServiceType serviceType, string updateType)
        //public IActionResult Update(ServiceType serviceType, string updateType)
        {
            ViewData["Title"] = "Editing a Service Type";

            var serviceTypes = _DbContext.ServiceTypes;
            //var webApi = new WebApiWrapper<ServiceType>(CommonCode.UrlCombine(CommonCode.GetAppUrl(HttpContext), "api", "ServiceTypeApi"));

            if (updateType.Equals("Delete"))
            {
                serviceTypes.Remove(serviceType);
                await _DbContext.SaveChangesAsync();

                //webApi.Delete(serviceType);

            }
            else
            {
                if (!ModelState.IsValid) return View("Edit", serviceType);

                serviceTypes.Update(serviceType);
                await _DbContext.SaveChangesAsync();

                //webApi.Put(serviceType);

            }
            return RedirectToAction(GetIndexAction());

        }

        private string GetIndexAction(string id = null)
        {
            return string.Format("{0}{1}", nameof(Index), id == null ? string.Empty : @"/" + id);
        }

        private readonly ApplicationDbContext _DbContext;
        public ServiceTypesController(ApplicationDbContext db) { _DbContext = db; } // ctor
        protected override void Dispose(bool disposing) { _DbContext.Dispose(); }

    } // class

} // namespace

SammysAuto/Views/Shared/_Edit.cshtml
@*
    This is a partial view for Edit template
*@


<br /><br />
<div class="row">
    <div class="form-group">
        <div class="col-md-2">@*Filler*@</div>
        @if (@Model.Id != 0)
        {
            <button type="submit" value="Update" name="updateType"
                    class="col-md-1 btn btn-info"
                    title="Save changes">
                <span class="glyphicon glyphicon-check"></span> Update
            </button>

            <div class="col-md-1">@*Filler*@</div>
            <button type="submit" value="Delete" name="updateType"
                    onclick="return confirm('Please select [Ok] to confirm...');"
                    class="col-md-1 btn btn-danger"
                    title="Remove this record">
                <span class="glyphicon glyphicon-remove-sign"></span> Delete
            </button>

        }
        else
        {
            <button type="submit" value="Add"
                    class="col-md-1 btn btn-info"
                    title="Add this record">
                <span class="glyphicon glyphicon-ok-sign"></span> Add
            </button>
        }

    </div>
</div>


<br /><br />
<div id="navlinks">
    <span>
        @Html.ActionLink(
                " Previous page"
                , (string)(ViewBag.PreviousAction == null ? "Index" : ViewBag.PreviousAction)
                , (string)(ViewBag.PreviousController == null ? ViewContext.RouteData.Values["controller"] : ViewBag.PreviousController)
                , (object)ViewBag.PreviousActionParameters

                , new
                    {
                        Class = "btn btn-link glyphicon glyphicon-list-alt"
                            ,
                        title = "Return to previous page"
                    }
                )
    </span>
</div>

SammysAuto/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
@RenderSection("Styles", required: false)
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sammy's Auto</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">SammysAuto</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Customers" asp-action="Index">Customers</a></li>
                    <li><a asp-area="" asp-controller="ServiceTypes" asp-action="Index">Service Types</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - SammysAuto</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

SammysAuto/Views/Shared/_List.cshtml
@*
    This is a partial view for List template
*@



<br /><br />
<div id="navlinks">
    @if (ViewBag.PreviousAction != null)
    {@*this <span> block is generated conditionally*@
    <span>
        @Html.ActionLink(
                " Previous page"
                , (string)ViewBag.PreviousAction
                , (string)ViewBag.PreviousController
                , (object)ViewBag.PreviousActionParameters
                , new
                    {
                        Class = "btn btn-link glyphicon glyphicon-list-alt"
                            ,
                        title = "Return to previous page"
                    }
                )
    </span>
}


    @if (ViewBag.CrudAction != null)
    {@*this <span> block is generated conditionally*@
    <span style="float:right">
        @Html.ActionLink(
                " Add new..."
                , (string)ViewBag.CrudAction
                , (string)(ViewBag.AddController == null ? ViewContext.RouteData.Values["controller"] : ViewBag.AddController)
                , (object)ViewBag.CrudActionParameters
                , new
                {
                    Class = "btn btn-link glyphicon glyphicon-plus-sign"
                            ,
                    title = "Add a new record"
                }
                )
    </span>
}
</div>